version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "socket-chat-db"
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
    ports:
      - 5432:5432
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql