on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build server
        run: cd server/src && cargo build --release
      - name: Build client
        run: cd client/src && cargo build --release